#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 25 14:16:11 2020

@author: SteliosMavrotas
"""

import pandas as pd
import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt

def accessdata(stocklist):
    d,dates=[],[]
    for i in stocklist:
        tckr=i
        a=yf.Ticker(i)
        prices=a.history(period='max',interval='1d')
        prices=prices.drop(prices.index[np.where(prices.index<'2008-01-07 00:00:00')])
        allData[i]=prices['Close']
        prices.to_csv('InvestingDGR/'+i+'.csv')
        d.append(min(prices.index))
        dates.append(i+" "+str(min(prices.index)))
        allData.index=prices.index
        
    return allData
        
def rebalance(index,allData,stocklist):
    loc=allData.index.get_loc(index)
    
    if str(index)=='2008-01-07 00:00:00':
        allData['Value'][index]=initialCapital
        "Total Value at t=0"
        
        allData['Cash'][index]=allData['Value'][index]- \
        sum([allData['Value '+i][index] for i in stocklist]) 
        "Cash at t=0"
        
    else:
        allData['Value'][index]=sum([allData['Value '+i][index] for i in stocklist]) \
        +allData['Cash'][index]
        
    for i in stocklist:
        allData['Shares '+i][index]=round(allData['Value'][index]*dic[i]/allData[i][index],0)
        "Shares at t=0 == Roundown(total value*weight/price)"
    
    return allData

def initialize(stocklist):
    for i in stocklist:
        allData['Value '+i]=pd.DataFrame(np.zeros(len(allData)))
        allData['Shares '+i]=pd.DataFrame(np.zeros(len(allData)))
    allData['Cash']=pd.DataFrame(np.zeros(len(allData)))
    
    return allData

def computeParameters(stocklist,allData):
    "To compute in Normal events (Not Start and Rebalacing)"
    
    for i in stocklist:
        allData['PnL']=allData['Value '+i][index]
        allData['Value '+i][index]=allData['Shares '+i]*allData[i]
        allData['Value'][index]+=allData['Value '+i][index]
        
    allData['Value'][index]+=allData['Cash'][index]
    
    return allData

if __name__=="__main__":
    stocklist=['TLT','SPEM','IVV','XLF','XLY','XLI','IAU','SLV','USO','UNG']

    count=-1
